"""JSON schemas used for LLM structured extraction."""

DESIGN_BRIEF_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": [
        "language",
        "product_category",
        "target_user",
        "use_case",
        "style_keywords",
        "functional_requirements",
        "material_preferences",
        "constraints",
        "missing_info",
    ],
    "properties": {
        "language": {"type": "string", "enum": ["en", "zh"]},
        "product_category": {"type": "string"},
        "target_user": {"type": "string"},
        "use_case": {"type": "string"},
        "style_keywords": {"type": "array", "items": {"type": "string"}},
        "functional_requirements": {"type": "array", "items": {"type": "string"}},
        "material_preferences": {"type": "array", "items": {"type": "string"}},
        "constraints": {"type": "array", "items": {"type": "string"}},
        "missing_info": {"type": "array", "items": {"type": "string"}},
    },
}

SERVICE_ISSUE_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": [
        "language",
        "machine_model",
        "serial_number",
        "machine_code",
        "issue_type",
        "symptoms",
        "alarm_info",
        "production_status",
        "urgency",
        "onsite_required",
        "parts_clues",
        "evidence_status",
        "factory_location",
        "customer_contact",
        "online_steps_attempted",
        "missing_info",
    ],
    "properties": {
        "language": {"type": "string", "enum": ["en", "zh"]},
        "machine_model": {"type": "string"},
        "serial_number": {"type": "string"},
        "machine_code": {"type": "string"},
        "issue_type": {"type": "string"},
        "symptoms": {"type": "array", "items": {"type": "string"}},
        "alarm_info": {"type": "string"},
        "production_status": {"type": "string", "enum": ["stopped", "reduced_speed", "running", "unknown"]},
        "urgency": {"type": "string", "enum": ["P1", "P2", "P3"]},
        "onsite_required": {"type": "boolean"},
        "parts_clues": {"type": "array", "items": {"type": "string"}},
        "evidence_status": {"type": "string"},
        "factory_location": {"type": "string"},
        "customer_contact": {"type": "string"},
        "online_steps_attempted": {"type": "array", "items": {"type": "string"}},
        "missing_info": {"type": "array", "items": {"type": "string"}},
    },
}

KNITTING_RECOMMENDATION_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": [
        "product_category",
        "target_user",
        "use_case",
        "style_direction",
        "functional_requirements",
        "yarn",
        "knit_structure",
        "machine",
        "recommendation_reasoning",
        "risks",
        "missing_info",
    ],
    "properties": {
        "product_category": {"type": "string"},
        "target_user": {"type": "string"},
        "use_case": {"type": "string"},
        "style_direction": {"type": "string"},
        "functional_requirements": {"type": "array", "items": {"type": "string"}},
        "yarn": {"type": "string"},
        "knit_structure": {"type": "string"},
        "machine": {"type": "string"},
        "recommendation_reasoning": {"type": "array", "items": {"type": "string"}},
        "risks": {"type": "array", "items": {"type": "string"}},
        "missing_info": {"type": "array", "items": {"type": "string"}},
    },
}

DIGITAL_TWIN_PLAN_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": [
        "sws_project_id",
        "preview",
        "parameter_package",
        "estimated_sample_time",
        "estimated_unit_cost",
        "estimated_yield",
        "risks",
        "next_actions",
        "missing_info",
    ],
    "properties": {
        "sws_project_id": {"type": "string"},
        "preview": {"type": "string"},
        "parameter_package": {
            "type": "object",
            "additionalProperties": False,
            "required": ["gauge", "machine", "structure", "yarn", "key_zones"],
            "properties": {
                "gauge": {"type": "string"},
                "machine": {"type": "string"},
                "structure": {"type": "string"},
                "yarn": {"type": "string"},
                "key_zones": {"type": "array", "items": {"type": "string"}},
            },
        },
        "estimated_sample_time": {"type": "string"},
        "estimated_unit_cost": {"type": "string"},
        "estimated_yield": {"type": "string"},
        "risks": {"type": "array", "items": {"type": "string"}},
        "next_actions": {"type": "array", "items": {"type": "string"}},
        "missing_info": {"type": "array", "items": {"type": "string"}},
    },
}

SERVICE_DISPATCH_PLAN_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": [
        "ticket_id",
        "issue_category",
        "machine_model",
        "serial_number",
        "production_status",
        "priority",
        "factory_location",
        "customer_contact",
        "assigned_engineer",
        "recommended_parts",
        "eta",
        "status",
        "dispatch_rationale",
        "online_steps_attempted",
        "customer_message",
        "missing_info",
    ],
    "properties": {
        "ticket_id": {"type": "string"},
        "issue_category": {"type": "string"},
        "machine_model": {"type": "string"},
        "serial_number": {"type": "string"},
        "production_status": {"type": "string"},
        "priority": {"type": "string"},
        "factory_location": {"type": "string"},
        "customer_contact": {"type": "string"},
        "assigned_engineer": {"type": "string"},
        "recommended_parts": {"type": "array", "items": {"type": "string"}},
        "eta": {"type": "string"},
        "status": {"type": "string"},
        "dispatch_rationale": {"type": "array", "items": {"type": "string"}},
        "online_steps_attempted": {"type": "array", "items": {"type": "string"}},
        "customer_message": {"type": "string"},
        "missing_info": {"type": "array", "items": {"type": "string"}},
    },
}
